# Generated by Django 4.1 on 2022-08-13 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0002_myuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="age",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
