# Generated by Django 4.1 on 2022-08-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0003_alter_myuser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
