# Generated by Django 4.1 on 2022-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course", name="content", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="course", name="title", field=models.CharField(max_length=255),
        ),
    ]
